apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
      - name: bookstore-backend
        image: your-username/bookstore-backend
        ports:
        - containerPort: 5555
        env:
        - name: mongoDBURL
          value: "your-mongodb-connection-string"
        - name: PORT
          value: "5555"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-service
spec:
  type: ClusterIP
  selector:
    app: bookstore-backend
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
