apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
      - name: bookstore-frontend
        image: your-username/bookstore-frontend
        ports:
        - containerPort: 3400
        env:
        - name: PORT
          value: "3400"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: bookstore-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3400
